#! /usr/bin/zsh

#this file test shell expression

FILE=~/test.bnq
ANSWER=maybe
INT=-5


# this is file expression
if [ -e $FILE ]; then
    if [ -f $FILE ]; then
	echo $FILE is a file
    fi

    if [ -d $FILE ]; then
	echo $FILE is a directory
    fi

    if [ -r $FILE ]; then
	echo $FILE is readable
    fi

    if [ -w $FILE ]; then
	echo $FILE is writable
    fi

    if [ -x $FILE ]; then
	echo $FILE is executable/searchable
    fi
else
    echo $FILE does not exist
    return 1
fi


#String expression
if [ -z "$ANSWER" ]; then
    echo "There is no answer." >&2
    exit 1
fi
if [ "$ANSWER" = "yes" ]; then
    echo "The answer is YES."
elif [ "$ANSWER" = "no" ]; then
    echo "The answer is NO."
elif [ "$ANSWER" = "maybe" ]; then
    echo "The answer is MAYBE."
else
    echo "The answer is UNKNOWN."
fi

#int expression
if [ -z $INT ]; then
    echo "INT is empty." >&2
    exit 1

fi

if [ $INT -eq 0 ]; then
    echo INT is zero.
else
    if [ $INT -lt 0 ]; then
        echo INT is negative.
    else
        echo INT is positive.
    fi
    if [ $(($INT % 2)) -eq 0 ]; then
        echo INT is even.
    else
        echo INT is odd.
    fi
fi


if [[ $INT =~ ^-?[0-9]+$ ]]; then
    if [[ $INT -eq 0 ]]; then
	echo INT is zero
    else
	if ((INT < 0)); then
	    echo INT is negative
	else
	    echo INT is positive
        fi

	if ((INT % 2 == 0)); then
	    echo INT is even
	else
	    echo INT is odd
	fi
    fi
else
    echo INT is not a integer >&2
    exit 1
fi
