#! /usr/bin/zsh

# Program to output a system information page

TITLE="System information Report For $HOSTNAME"

CURRENT_TIME=$(date)

TIME_STAMP="Generated $CURRENT_TIME, by $USER"

report_uptime () {
    cat << EOF
    <H2>System Uptime</H2>
    <PRE>$(uptime)</PRE>
EOF
     return
}

function report_disk_space {
    cat <<EOF
    <H2>Disk Space Utilization</H2>
    <PRE>$(df -h)</PRE>
EOF
}

report_home_space () {
    if (( $(id -u) == 0 )); then
	cat << EOF
        <H2>Home Space Utilization (All Users)</H2>
        <PRE>$(du -sh /home/*)</PRE>
EOF
    else
        cat <<- _EOF_
        <H2>Home Space Utilization</H2>
        <PRE>$(du -sh $HOME)</PRE>
_EOF_
    fi
  return
}


cat << EOF

<HTML>
    <HEAD>
          <TITLE>$TITLE</TITLE>
    </HEAD>
    <BODY>
          <H1>$TITLE</H1>
          <P>$TIME_STAMP</P>
          $(report_uptime)
          $(report_disk_space)
          $(report_home_space)
    </BODY>
</HTML>


EOF
